services:
  postgres:
    image: postgres:16.4-alpine
    container_name: sql-data-warehouse-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: datawarehouse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./datasets:/datasets:ro

volumes:
  postgres_data:
